service: karma-weekly-graphql

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: us-east-1
  environment:
    USER_TABLE_NAME: "${self:service}-${opt:stage, self:provider.stage}-user"
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - ses:SendEmail
      Resource: "*"

functions:
  sendSubredditNewsletters:
    handler: handler.sendSubredditNewsletters
    memorySize: 512

  graphql:
    handler: handler.graphql
    memorySize: 512
    events:
      - http:
          path: graphql
          method: post
          cors: true
          integration: lambda-proxy

resources:
  Resources:
    UsersDynamoDbTable:
      Type: "AWS::DynamoDB::Table"
      DeletionPolicy: Retain
      Properties:
        TableName: ${self:provider.environment.USER_TABLE_NAME}
        AttributeDefinitions:
          - AttributeName: "email"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "email"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
